apiVersion: v1
kind: Pod
metadata:
  name: postalcode-app-pod
spec:
  containers:
  - name: postalcode-app
    image: postalcode-app:1
    imagePullPolicy: Never
    env:
    - name: MOCKSERVER_INITIALIZATION_JSON_PATH
      value: "config/mockserverInitialization.json"
